version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    ports:
      - "1883:1883"
    configs:
      - source: mosquitto_config
        target: /mosquitto/config/mosquitto.conf

  influxdb:
    image: influxdb:2.7-alpine
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUX_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUX_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUX_ADMIN_TOKEN}
      - DOCKER_INFLUXDB_INIT_ORG=water-the-plants
      - DOCKER_INFLUXDB_INIT_BUCKET=moisture
    volumes:
      - influx_data:/var/lib/influxdb2

  telegraf:
    image: telegraf:1.34-alpine
    container_name: telegraf
    configs:
      - source: telegraf_config
        target: /etc/telegraf/telegraf.conf

configs:
  telegraf_config:
    file: ./telegraf.conf
  mosquitto_config:
    file: ./mosquitto.conf

volumes:
  influx_data:
